### ISSUE TITLE
Make php function called 'deactivate_all_activated_questions' fire when the instructor clicks deactivate all questions

### ISSUE THREAD

**Issue by drumm91UWO** [drumm91UWO/WebDevTeam5#13]

**Comment by Sammerz309** [comment]
I will work on this today

**Comment by drumm91UWO** [comment]
I had to make javascript code for this anyways.

In php or html file:
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

In javascript:
$.ajax({
        type: 'POST',
        data: {},
        url: '../Database_files/attempttoactivatequestion.php',//you may have to change this file path
        success: function (data) {
            //alert(data);
        },
        error: function (xhr) {
            alert("error");
        }
    });

**Comment by drumm91UWO** [comment]
Feel free to use this code in your solution to this issue.

**Comment by Sammerz309** [comment]
What does this javascript do? haha
