### ISSUE TITLE
Make the instructor's editquestion.html page function (as usual, click here for details)

### ISSUE THREAD

**Issue by drumm91UWO** [drumm91UWO/WebDevTeam5#14]
Look at activatequestion.php for inspiration. editquestion.html and references to it should probably be changed to editquestion.php

**Comment by drumm91UWO** [comment]
Hello Rajesh,

I am going to start working on the editquestion.php file to get you started. I will create a button that will execute a php function called edit_question($id, $status, $statement, $answer, $points, $description, $keywords, $section, $graderCode). This function will make any changes to the question attributes that they like. The $id parameter will never be null. The other parameters may be null. If a parameter is null, then no change to that attribute will occur. Does this make sense?

Would you like to make this function? If so, put it in the queries.php file. Test it with the editquestion.php interface that I will provide (later today).

In order to test, you will need to use the repository and the webdev server. I am available all weekend if you would like to get together and work on this. I recommend you send me a time you are available. We can meet at UW Oshkosh. Although, I live in Neenah. You can come over to my apartment, we can meet at a library, coffee shop, etc. Just let me know. I want to give you the opportunity to contribute to this project.

**Comment by drumm91UWO** [comment]
My part is done.

**Comment by dhirar25** [comment]
Thanks for email. I will work on it after 2:00 pm today. I will be in library today and tomorrow. If I need help tomorrow I will let you know then we can figure it out where we can met.
Thanks

**Comment by drumm91UWO** [comment]
Ok
